#Stage For Trivy Vulerability Scanner
FROM python:3.11 AS scanning-stage
LABEL app="BOTO3 with FastAPI"
WORKDIR /code
COPY main.py main.py
ADD templates templates
COPY --from=aquasec/trivy:latest /usr/local/bin/trivy /usr/local/bin/trivy
RUN trivy filesystem -f json --scanners vuln,secret,misconfig --exit-code 0 --no-progress > /tmp/trivy.json / \
    && trivy --version

#Stage For Installing Python & APT Dependencies
FROM python:3.11 AS build-stage
WORKDIR /code
COPY requirements.txt requirements.txt
COPY --from=scanning-stage /tmp/trivy.json /tmp/trivy.json
#RUN pip install --no-cache-dir --upgrade -r requirements.txt \
RUN apt update && apt install -y unzip --allow-unauthenticated
ARG T_VERSION=1.9.1
ADD https://releases.hashicorp.com/terraform/${T_VERSION}/terraform_${T_VERSION}_linux_amd64.zip terraform.zip
RUN unzip terraform.zip -d /usr/local/bin

# Stage For Building Image
FROM python:3.11 AS image-stage
LABEL app="BOTO3 with FastAPI"
ENV AWS_DEFAULT_REGION=us-east-1
ENV AWS_ACCESS_KEY_ID=AKIAUBKFCGI72IWHHHEY
ENV AWS_SECRET_ACCESS_KEY=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
WORKDIR /code
COPY --from=build-stage /usr/local/lib/python3.11 /usr/local/lib/python3.11
COPY --from=build-stage /usr/local/bin/terraform /usr/local/bin/terraform
COPY --from=scanning-stage /tmp/trivy.json /tmp/trivy.json
COPY main.py main.py
ADD templates templates
ADD Instructions.info Instructions.txt
COPY requirements.txt requirements.txt
RUN terraform version && pip install --no-cache-dir --upgrade -r requirements.txt 
EXPOSE 80
ENTRYPOINT ["uvicorn", "main:app", "--host", "0.0.0.0"]
CMD ["--port", "80"]