version: '3'

services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'mongoadmin'
      MONGO_INITDB_ROOT_PASSWORD: 'secret'
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/db:rw'
    networks:
      - 'mongodbnw'
    depends_on:
      - mongo-express

  mongo-express:
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: 'mongoadmin'
      ME_CONFIG_MONGODB_ADMINPASSWORD: 'secret'
      ME_CONFIG_OPTIONS_EDITORTHEME: 'ambiance'
      ME_CONFIG_MONGODB_SERVER: 'mongo'
      ME_CONFIG_BASICAUTH_USERNAME: 'mongoadmin'
      ME_CONFIG_BASICAUTH_PASSWORD: 'secret'
    ports:
      - '8081:8081'
    networks:
      - 'mongodbnw'
volumes:
  mongo:
    name: 'mongo'
    driver: local

networks:
  mongodbnw:
    driver: bridge
    name: 'mongodbnw'
